spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Це дозволить автоматично створювати таблиці з твоїх @Entity класів
spring.jpa.hibernate.ddl-auto=update
# Щоб бачити в консолі, які SQL запити робить Spring
spring.jpa.show-sql=true